/* Consulta que devuelve las personas entre 20 y 30 años, que salen de la ciudad de Washington. */ 
SELECT P.NOMBRES, P.APELLIDOS, P.TIPODOC, P.NUMDOC, P.EDAD, C.NOMBRE AS ORIGEN FROM AEROPUERTO.CIUDAD C, AEROPUERTO.PASAJERO P, AEROPUERTO.TIQUETE T, AEROPUERTO.RUTA R, AEROPUERTO.VUELO V
WHERE R.ID = V.IDRUTA 
AND V.ID = T.IDVUELO
AND P.ID = T.IDPASAJERO
AND R.IDCORIGEN = C.ID
AND C.NOMBRE = 'WASHINGTON'
AND P.EDAD BETWEEN 20 AND 30;

/* Consulta la información referente a los vuelos de una persona usando su documento de identificación */
SELECT P.NUMDOC, P.NOMBRES, P.APELLIDOS, C1.NOMBRE AS ORIGEN, C2.NOMBRE AS DESTINO, H.ABORDAJE, H.DESPEGUE, H.ATERRIZAJE
FROM AEROPUERTO.CIUDAD C1, AEROPUERTO.CIUDAD C2, AEROPUERTO.PASAJERO P, AEROPUERTO.TIQUETE T, AEROPUERTO.RUTA R, AEROPUERTO.VUELO V, AEROPUERTO.HORARIO H
WHERE R.ID = V.IDRUTA 
AND V.ID = T.IDVUELO
AND P.ID = T.IDPASAJERO
AND H.ID = V.IDHORARIO
AND R.IDCORIGEN = C1.ID
AND R.IDCDESTINO = C2.ID
AND P.NUMDOC = '1005874567';

/* Consulta que devuelve los auxiliares de un conjunto de vuelos */
SELECT A.NOMBRES, A.APELLIDOS, A.EDAD, A.SEXO 
FROM AEROPUERTO.VUELO V, AEROPUERTO.AUXILIARESVUELO AV, AEROPUERTO.AUXILIAR A
WHERE V.ID = AV.IDVUELO
AND A.ID = AV.IDAUXILIAR
AND V.ID IN (1,2,3)

/* Consulta los vuelos de cierto día para una determinada aerolínea */
SELECT V.ID, C1.NOMBRE AS ORIGEN, C2.NOMBRE AS DESTINO, H.ABORDAJE, H.DESPEGUE, H.ATERRIZAJE
FROM AEROPUERTO.CIUDAD C1, AEROPUERTO.CIUDAD C2, AEROPUERTO.VUELO V, AEROPUERTO.HORARIO H, AEROPUERTO.RUTA R, AEROPUERTO.AVION AV, AEROPUERTO.AEROLINEA AE
WHERE V.IDHORARIO = H.ID
AND R.ID = V.IDRUTA 
AND R.IDCORIGEN = C1.ID
AND R.IDCDESTINO = C2.ID
AND AV.ID = V.IDAVION
AND AE.ID = AV.IDAEROLINEA
AND AE.NOMBRE = 'SATENA'
AND H.ABORDAJE::VARCHAR LIKE '2021-01-22%';

/* Consulta vuelos hacia una respectiva ciudad */
SELECT C1.NOMBRE AS ORIGEN, C2.NOMBRE AS DESTINO, H.ABORDAJE, H.DESPEGUE, H.ATERRIZAJE
FROM AEROPUERTO.CIUDAD C1, AEROPUERTO.CIUDAD C2, AEROPUERTO.VUELO V, AEROPUERTO.HORARIO H, AEROPUERTO.RUTA R, AEROPUERTO.AVION AV, AEROPUERTO.AEROLINEA AE
WHERE V.IDHORARIO = H.ID
AND R.ID = V.IDRUTA 
AND R.IDCORIGEN = C1.ID
AND R.IDCDESTINO = C2.ID
AND AV.ID = V.IDAVION
AND AE.ID = AV.IDAEROLINEA
AND C2.NOMBRE = 'BOGOTA';

/* Consulta que devuelve los vuelos que llegaron a BUCARAMANGA entre Enero y Febrero de 2021 */

SELECT V.ID AS VUELO, V.IDAVION, V.IDPILOTO, V.IDCOPILOTO, V.IDRUTA, C.NOMBRE AS DESTINO, V.IDHORARIO, H.ATERRIZAJE AS FECHALLEGADA
FROM AEROPUERTO.VUELO V,  AEROPUERTO.CIUDAD C, AEROPUERTO.RUTA R, AEROPUERTO.HORARIO H
WHERE V.IDRUTA=R.ID
AND R.IDCDESTINO=C.ID
AND V.IDHORARIO=H.ID
AND H.ATERRIZAJE >= DATE('2021-01-01') AND H.ATERRIZAJE < DATE('2021-03-01')
AND C.NOMBRE ='BUCARAMANGA'

/* Bloque anónimo que muestra los vuelos de cada aerolínea */
DO $$
DECLARE
 CONTADOR INTEGER = 0;
 REGISTRO RECORD;
 POINTER CURSOR(IDAE INTEGER)
 FOR SELECT AE.NOMBRE, C1.NOMBRE AS ORIGEN, C2.NOMBRE AS DESTINO, H.ABORDAJE
 FROM AEROPUERTO.AEROLINEA AE, AEROPUERTO.VUELO V, AEROPUERTO.AVION AV, AEROPUERTO.HORARIO H, AEROPUERTO.RUTA R, AEROPUERTO.CIUDAD C1, AEROPUERTO.CIUDAD C2
 WHERE 
	AV.IDAEROLINEA = IDAE
	AND AE.ID = IDAE
	AND R.ID = V.IDRUTA 
	AND R.IDCORIGEN = C1.ID
	AND R.IDCDESTINO = C2.ID
	AND AV.ID = V.IDAVION
	AND V.IDHORARIO = H.ID;
BEGIN
   FOR I IN 1..3 LOOP
	   OPEN POINTER(I);
	   FETCH POINTER INTO REGISTRO;
	   RAISE NOTICE '%', I || '. ' || REGISTRO.NOMBRE ;
	   LOOP
	   		CONTADOR = CONTADOR+1;
			RAISE NOTICE '%',  '		' || CONTADOR || '. ' || REGISTRO.ORIGEN || ' - ' || REGISTRO.DESTINO || ' - '  || REGISTRO.ABORDAJE;
			FETCH POINTER INTO REGISTRO;
			EXIT WHEN NOT FOUND;
	   END LOOP;
	   CLOSE POINTER;
   END LOOP;
END; $$