SELECT * FROM AEROPUERTO.CIUDAD

SELECT * FROM AEROPUERTO.DETALLEAEROLINEAS

SELECT * FROM AEROPUERTO.SILLA

/* Consulta que devuelve las personas entre 20 y 30 años, que salen de la ciudad de Bogotá. */ 
SELECT P.NOMBRES, P.APELLIDOS, P.TIPODOC, P.NUMDOC, P.EDAD, C.NOMBRE AS ORIGEN FROM AEROPUERTO.CIUDAD C, AEROPUERTO.PASAJERO P, AEROPUERTO.TIQUETE T, AEROPUERTO.RUTA R, AEROPUERTO.VUELO V
WHERE R.ID = V.IDRUTA 
AND V.ID = T.IDVUELO
AND P.ID = T.IDPASAJERO
AND R.IDCORIGEN = C.ID
AND C.NOMBRE = 'WASHINGTON'
AND P.EDAD BETWEEN 20 AND 30;

/* Consulta la información referente a los vuelos de una persona usando su documento de identificación */
SELECT P.NUMDOC, P.NOMBRES, P.APELLIDOS, C1.NOMBRE AS ORIGEN, C2.NOMBRE AS DESTINO, H.ABORDAJE, H.DESPEGUE, H.ATERRIZAJE
FROM AEROPUERTO.CIUDAD C1, AEROPUERTO.CIUDAD C2, AEROPUERTO.PASAJERO P, AEROPUERTO.TIQUETE T, AEROPUERTO.RUTA R, AEROPUERTO.VUELO V, AEROPUERTO.HORARIO H
WHERE R.ID = V.IDRUTA 
AND V.ID = T.IDVUELO
AND P.ID = T.IDPASAJERO
AND H.ID = V.IDHORARIO
AND R.IDCORIGEN = C1.ID
AND R.IDCDESTINO = C2.ID
AND P.NUMDOC = '1005874567';

/* Consulta la tripulación a cargo de un vuelo dado su ID */
SELECT 

/* Consulta los vuelos de cierto día para una determinada aerolínea */
SELECT V.ID, C1.NOMBRE AS ORIGEN, C2.NOMBRE AS DESTINO, H.ABORDAJE, H.DESPEGUE, H.ATERRIZAJE
FROM AEROPUERTO.CIUDAD C1, AEROPUERTO.CIUDAD C2, AEROPUERTO.VUELO V, AEROPUERTO.HORARIO H, AEROPUERTO.RUTA R, AEROPUERTO.AVION AV, AEROPUERTO.AEROLINEA AE
WHERE V.IDHORARIO = H.ID
AND R.ID = V.IDRUTA 
AND R.IDCORIGEN = C1.ID
AND R.IDCDESTINO = C2.ID
AND AV.ID = V.IDAVION
AND AE.ID = AV.IDAEROLINEA
AND AE.NOMBRE = 'SATENA'
AND H.ABORDAJE::VARCHAR LIKE '2021-01-22%';

/* Consulta vuelos hacia una respectiva ciudad */
SELECT C1.NOMBRE AS ORIGEN, C2.NOMBRE AS DESTINO, H.ABORDAJE, H.DESPEGUE, H.ATERRIZAJE
FROM AEROPUERTO.CIUDAD C1, AEROPUERTO.CIUDAD C2, AEROPUERTO.VUELO V, AEROPUERTO.HORARIO H, AEROPUERTO.RUTA R, AEROPUERTO.AVION AV, AEROPUERTO.AEROLINEA AE
WHERE V.IDHORARIO = H.ID
AND R.ID = V.IDRUTA 
AND R.IDCORIGEN = C1.ID
AND R.IDCDESTINO = C2.ID
AND AV.ID = V.IDAVION
AND AE.ID = AV.IDAEROLINEA
AND C2.NOMBRE = 'BOGOTA';