 CREATE SCHEMA HOTELBD;

CREATE TABLE HOTELBD.MODOPAGO
(
Id INt PRIMARY KEY,
ModoPago VARCHAR(50)
);


CREATE TABLE HOTELBD.TIPOHABITACION
(
Id INt PRIMARY KEY,
Tipo VARCHAR(50)
);

CREATE TABLE HOTELBD.MARCA
(
Id INt PRIMARY KEY,
Nombre VARCHAR(50)
);

CREATE TABLE HOTELBD.TIPOBEBIDAS
(
Id INt PRIMARY KEY,
Nombre VARCHAR(50)
);

CREATE TABLE HOTELBD.TIPOMARCA
(
Id  INt PRIMARY KEY,
Nombre VARCHAR(50),
Precio MONEY,
IdMarca INT,
IdTipoBebidas INT,
CONSTRAINT FK_Id_Marca FOREIGN KEY (IdMarca) REFERENCES HOTELBD.MARCA (Id),
CONSTRAINT FK_Id_Tipo_Bebidas1 FOREIGN KEY (IdTipoBebidas) REFERENCES HOTELBD.TIPOBEBIDAS (Id)
);


CREATE TABLE HOTELBD.MINIBAR
(
Id INt PRIMARY KEY,
Nombre VARCHAR(50),
Telefono VARCHAR(50)
);


CREATE TABLE HOTELBD.MINIRESTAURANTE 
(
Id  INt PRIMARY KEY,
Nombre VARCHAR(50),
Telefono VARCHAR(50)
);

CREATE TABLE HOTELBD.BEBIDAS
(
Id  INt PRIMARY KEY,
IdMarca INT,
IdMinibar INT,
CONSTRAINT FK_Id_Marca1 FOREIGN KEY (IdMarca) REFERENCES HOTELBD.MARCA(Id ),
CONSTRAINT FK_Id_Minibar FOREIGN KEY (IdMinibar) REFERENCES HOTELBD.MINIBAR (Id)
);



CREATE TABLE HOTELBD.HOTEL
(
  id int PRIMARY KEY,
  nombre character varying(50),
  direccion character varying(50),
  telefono character varying(50),
  idminibar integer,
  idminirestaurante integer,
  CONSTRAINT fk_id_mini_restaurante FOREIGN KEY (idminirestaurante)
      REFERENCES hotelbd.minirestaurante (id),
  CONSTRAINT fk_id_minibar2 FOREIGN KEY (idminibar)
      REFERENCES hotelbd.minibar (id) 
);

CREATE TABLE HOTELBD.HOTELBAR
(
Id  INt PRIMARY KEY,
IdHotel INT,
IdMinibar INT,
CONSTRAINT FK_Id_Hotel2 FOREIGN KEY (IdHotel) REFERENCES HOTELBD.HOTEL(Id ),
CONSTRAINT FK_Id_Minibar FOREIGN KEY (IdMinibar) REFERENCES HOTELBD.MINIBAR (Id)
);

CREATE TABLE HOTELBD.HOTELRESTAURANTE
(
Id  INt PRIMARY KEY,
IdHotel INT,
IdMiniRestaurante INT,
CONSTRAINT FK_Id_Hotel2 FOREIGN KEY (IdHotel) REFERENCES HOTELBD.HOTEL(Id ),
CONSTRAINT FK_Id_Mini_Restaurante FOREIGN KEY (IdMiniRestaurante) REFERENCES HOTELBD.MINIRESTAURANTE (Id)
);

CREATE TABLE HOTELBD.TIPOEMPLEADO
(
Id  INt PRIMARY KEY,
Cargo VARCHAR(50),
Salario MONEY
);


CREATE TABLE HOTELBD.EMPLEADO
(
Id  INt PRIMARY KEY,
Nombre VARCHAR(50),
Apellido VARCHAR(50),
Edad VARCHAR(50),
Sexo CHAR(50),
Telefono VARCHAR(50),
Direccion VARCHAR(50),
TarjetaIdentidad VARCHAR(50),
Turno VARCHAR(50),
IdHotel INT,
IdTipoEmpleado INT,
CONSTRAINT FK_Id_Hotel FOREIGN KEY (IdHotel) REFERENCES HOTELBD.HOTEL(Id),
CONSTRAINT FK_Id_Tipo_Empleado FOREIGN KEY (IdTipoEmpleado) REFERENCES HOTELBD.TIPOEMPLEADO (Id)
);

CREATE TABLE HOTELBD.CLIENTE
(
Id INt PRIMARY KEY,
Nombre VARCHAR(50),
Apellido VARCHAR(50),
Telefono VARCHAR(50),
TarjetaIdentidad VARCHAR(50),
Direccion VARCHAR (50),
IdModoPago INT,
IdEmpleado INT,
CONSTRAINT FK_Id_Empleado FOREIGN KEY (IdEmpleado) REFERENCES HOTELBD.EMPLEADO (Id),
CONSTRAINT FK_Id_Modo_Pago2 FOREIGN KEY (IdModoPago) REFERENCES HOTELBD.MODOPAGO (Id)
);



CREATE TABLE HOTELBD.ESTANCIA
(
Id INt PRIMARY KEY,
FechaEntrada DATE,
FechaSalida DATE,
IdModoPago INT,
IdCliente INT,
CONSTRAINT FK_Id_Modo_Pago FOREIGN KEY(IdModoPago) REFERENCES  HOTELBD.MODOPAGO (Id), 
CONSTRAINT FK_Id_Cliente FOREIGN KEY(IdCliente) REFERENCES  HOTELBD.CLIENTE (Id)
);


CREATE TABLE HOTELBD.HABITACION
(
Id INt PRIMARY KEY,
NumeroHabitacion VARCHAR(50),
IdHotel INT,
IdTipoHabitacion INT,
CONSTRAINT FK_Id_Hotel1 FOREIGN KEY (IdHotel) REFERENCES HOTELBD.HOTEL (Id),
CONSTRAINT FK_Id_Tipo_Habitacion FOREIGN KEY (IdTipoHabitacion) REFERENCES HOTELBD.TIPOHABITACION (Id)
);

CREATE TABLE HOTELBD.CLIENTEHABITACION
(
Id INt PRIMARY KEY,
IdCliente INT,
IdHabitacion INT,
CONSTRAINT FK_Id_Cliente2  FOREIGN KEY (IdCliente ) REFERENCES HOTELBD.CLIENTE (Id),
CONSTRAINT FK_Id_Habitacion  FOREIGN KEY (IdHabitacion) REFERENCES HOTELBD.HABITACION (Id)
);

CREATE TABLE HOTELBD.MAPAUBICACION
(
Id INt PRIMARY KEY,
NombreCliente VARCHAR(50),
Capital VARCHAR (50),
Departamento VARCHAR(50),
Pais VARCHAR(50),
Longitud REAL NOT NULL,
Latitud REAL NOT NULL,
Visitas INT
);
